= Notities voor Nederlands leren
Nian Liu <https://www.linkedin.com/in/nliu89>
:sectnums:
:toc:

== Zinsbouw basiszinnen

https://www.dutchgrammar.com/nl/?n=WordOrder.00

https://zichtbaarnederlands.nl/nl/zinsbouw/zinsbouw

=== De hoofdzin

`*wie/wat + werkwoord + wanneer + object + waar*` +
Jij eet vandaag een appel op school.

`Na de woorden: *want*, *maar*, *en*, *of*, *dus*.` +
Ik kom niet naar school want ik ben ziek.

=== Inversie

==== Vraagzin met werkwoord

`*werkwoord + wie/wat + wanneer + object + waar*` +
Eet jij vandaag een appel op school?

==== Vraagzin met vraagwoord

`*vraagwoord + werkwoord + wie/wat + wanneer + waar*` +
Wat eet jij vandaag op school?

==== Gewone zin met inversie - Je begint met iets anders

`*iets anders + werkwoord + wie/wat + object*` +
Vandaag eet jij een appel. +
Op school eet jij vandaag een appel.

_Iets anders zoals de woorden: nu, dan, straks, gisteren, eerst, daarna, daarom, toch, misschien, in Hilversum, op school, hier._

=== De bijzin

`*Omdat + wie/wat + wanneer + object + waar + werkwoord(en)*` +
Omdat ik vandaag ziek thuis ben.
Omdat ik gisteren ziek ben geweest.

* `Na de woorden: *als*, *terwijl*, *hoewel*, *toen*, *dat*, *die*, *en na*`
* `Vraagwoorden in het midden van de zin: ... *wie* ... *waar* ... *hoe* ...`

==== De bijzin, inversie

* Omdat ik vandaag ziek ben, kom ik niet naar school.
* Als ze verdrietig is, moet ze altijd huilen.
* Terwijl ik huiswerk maak, luister ik naar de radio.

== Spelling

=== Open / Gesloten lettergrepen

* Bij een *open lettergreep* is het zo, dat er een *klinker* aan het einde van de lettergreep staat.
* Bij een *gesloten lettergreep* zie je steeds een *medeklinker* aan het einde van de lettergreep staan.

=== Lange klank

Schrijft een lange klank met een klinker in een open lettergreep, en met twee klinkers in een gesloten lettergreep.

[%header,cols=3]
|===
| zijn / wij / jullie | lettergrepen | ik
| eten | e-ten | eet
| praten | pra-ten | praat
| lopen | lo-pen | loop
| lezen | le-zen | lees _(z -> s)_
| kopen | ko-pen | koop
| koppen | kop-pen | kop
| spellen | spel-len | spel
| spelen | spe-len | speel
| studeren | stu-de-ren | studeer _(*stu* keeps unchanged because it remains an open syllable)_
| sturen | stu-ren | stuur
| schrijven | schrij-ven | schrijf
| nemen | ne-men | neem
| staan | staan | sta
|===

=== Woordenlijst

[%header,cols=2]
|===
| Nederlands | Engles
| lettergreep / syllabe | syllable
| klinker | vowel
| medeklinker | consonant
| lange klank | long sound
| korte klank | short sound
| meervoud | plural
|===

== Klokkijken

|===
| 11:00 | elf uur
| 11:05 | vijf over elf
| 11:10 | tien over elf
| 11:15 | kwart over elf
| 11:20 | tien voor half twaalf
| 11:25 | vijf voor half twaalf
| 11:30 | half twaalf
| 11:35 | vijf over half twaalf
| 11:40 | tien over half twaalf
| 11:45 | kwart voor twaalf
| 11:50 | tien voor twaalf
| 11:55 | vijf voor twaalf
| 11:00 - 12:00 | een uur
| 11:00 - 11:30 | een halfuur
| 11:00 - 11:15 | een kwartier
| 11:00 - 11:01 | een minuut
|===

https://www.rekenen.nl/klokkijken/analoge-klok

== Vraagwoordvragen
* *Wie* is hun docent?
* *Hoe* gaat het met jou?
* *Hoeveel* dagen heeft een week?
* *Hoeveel* kost het?
* *Wat* is jouw naam?
* *Waar* ga je op vakantie?
* Op *welke* dag van de week hebben we de Nederlands les?
* *Wanneer* is jouw verjaardag?
* *Waarom* kom je naar Nederland?

== Cheatsheet
[%header,cols=7]
|===
| subject   | object    | possessief pronomen | reflexief pronomen  | werkwoorden | zijn  | hebben
| ik        | mij / me  | mijn                | me                  | de stam     | ben   | heb
| jij / je  | jou / je  | jouw / je           | je                  | stam + t    | bent  | hebt
| u         | u         | uw                  | u / zich            | stam + t    | bent  | hebt / heeft
| hij       | hem       | zijn                | zich                | stam + t    | is    | heeft
| zij / ze  | haar      | haar                | zich                | stam + t    | is    | heeft
| wij / we  | ons       | onze / ons          | ons                 | infinitief  | zijn  | hebben
| jullie    | jullie    | jullie              | je                  | infinitief  | zijn  | hebben
| zij / ze  | hen / ze  | hun                 | zich                | infinitief  | zijn  | hebben
|===

== Maanden en seizoenen

=== maanden

[grid=none]
|===
| januari | februari | maart | april
| mei | juni | juli | augustus
| september | oktober | november | december
|===

=== seizoenen

* de lente / het voorjaar
* de zomer
* de herfst / het najaar
* de winter

== Pluralis

[cols="1,5,4"]
|===

| -en | Het substantief krijgt *-en* wanneer het uit een syllabe bestaat | fietsen, boeken

.2+| -s
| Het substantief krijgt een *-s* wanneer het bestaat uit tweee of meer syllabes en eindigt op *-el*, *-em*, *-en*, *-er*, *-je* of *-e* | aardappels, modems, jongens, buitenlanders, biertjes, kantines
| Buitenlandse woorden krijgen meestal een *-s* | films, champignons

| '-s | Het eindigt op *-a*, *-i*, *-o*, *-u* of *-y* | paprika's, kiwi's, auto's, foto's, menu's, hobby's

| | Onregelmatige vormen | stad -> steden, kind -> kinderen, ei -> eieren

|===

== Modale werkwoorden
[cols=6]
|===
|                       | *mogen* | *willen* | *moeten* | *kunnen* | *zullen*
| ik | mag | wil | moet | kan | zal
| jij / je/ u | mag | wil / wilt | moet | kan / kunt | zal / zult
| hij / zij / ze / het | mag | wil | moet | kan | zal
| wij / we | mogen | willen | moeten | kunnen | zullen
| jullie | mogen | willen | moeten | kunnen | zullen
| zij / ze | mogen | willen | moeten | kunnen | zullen
|===

*Met infinitief*

Vaak komt er een infinitief na een modaal werkwoord.
Die infinitief staat meestal aan het einde van de zin.

* Mag ik tien meer minuten spelen? Ja, dat mag wel. / Nee, dat mag niet.
* Mag ik jouw soep ook even proeven?
* We moeten oefening 3 ook maken.

*Zonder infinitief*

* Ik will graag koffie.
* Ik moet naar de les.

== Graag / Liever / Het liefst

=== Zinsbouw
[cols=3]
|===
| *graag* | *liever* | *het liefst*
| `[wie/wat] + [werkwoord] + *graag* + [rest]`
| `[wie/wat] + [werkwoord] + *liever* + [rest] + (dan ...)`
| `[wie/wat] + [werkwoord] + *het liefst* + [rest]`
| Tom eet graag vlees.
| Ze eten liever groente dan vlees.
| We eten het liefst vis.
| Jip studeert graat in de bibliotheek.
| Esther gaat liever met de trein dan met de auto naar haar werk.
| Simon werk het liefst alleen.
|===

=== Ik wil graag
[cols=3]
|===
| ik wil = direct
| graag = polite
| zou graag = would like = event more polite
| Ik *wil* een ijsje!
| Ik *wil graag* een ijsje.
| Ik *zou graag* een ijsje *willen*.
| We *willen* een pauze.
| We *willen graag* een pauze.
| We *zouden graag* een pauze *willen*.

|===

=== Other ways to express "like something"

[cols=2]
|===
.3+| I like tea.
| Ik *drink graag* thee.
| Ik *hou van* thee.
| Ik *vind* thee *lekker*.
.3+| I like classic music.
| Ik *luister graag* klassieke muziek.
| Ik *hou van* klassieke muziek.
| Ik *vind* klassieke muziek *mooi / goed*.
|===

=== zou
==== Beleefde vraag

|===
| Zou + willen + infinitief

| Zou je mij willen helpen?

| `Zou + mogen (+ infiditief)`



`Zou + kunnen + infinitief`

|===

==== Wensen

== Perfectum
`*hebben* / *zijn* + participium van een werkwoord`

[cols=3]
|===

2+| | *Participium*
.2+| *Werkwoorden*
| regelmatig | *ge* + stam + *t / d*
| onregelmatig | uit het hoofd leren
|===

. Wanneer krijgt het participium een *-t* en wanneer een *-d*? +
  Luister naar de laaste letter van de stam. Hoe klinkt de laatste letter? Als:
** *s*, *f*, *t*, *k*, *ch*, of *p*  (**s**o**ft** **k**e**tch**u**p**)? Dan schrijf je `*ge* + stam + *t*` +
    infinitief: werken | stam: werk | participium: gewerkt

** een andere klank dan *s*, *f*, *t*, *k*, *ch*, of *p*? Dan schrijf je `*ge* + stam + *d*` +
    infinitief: spelen | stam: speel | participium: gespeeld

. Begint het werkwoord met *ge-*, *be-*, *her-*, *ver-* of *ont-*? Dan vervalt *ge-* +
    gebeuren -> gebeurd +
    betalen -> betaald +
    herhalen -> herhaald +
    vertalen -> vertaald +
    ontdekken -> ontdekt

. Wanneer gebruik je *zijn*? Wanneer gebruik je *hebben*? +
  Je gebruikt meestal *hebben* maar soms *zijn*. +
** *hebben* +
    We hebben gefietst. +
    Hij heeft zijn moeder gebeld. +
    Ik heb mijn zus geholpen.

** *zijn*
*** `richting` +
    Ik ben naar huis gefietst.
*** `verandering van situatie` +
    We zijn om 9.00 uur begonnen. +
    Ze is met de cursus gestopt. +
    Ben je gisteren 21 geworden? +
    Wat is er gebeurd?
*** `werkwoorden` +
    Ik ben naar de voetbalvereniging geweest.
    Hij is tot 22.00 uur gebleven.

[%header, cols=2]
|===
| presens | perfectum
| luisteren | geluisterd
| halen | gehaald
| spelen | gespeeld
| maken | gemaakt
| koken | gekookt
| wandelen _(schwa)_ | gewandeld
| leven | geleefd   (*v* staat niet in SOFT KETCHUP)
| reizen | gereisd   (*z* staat niet in SOFT KETCHUP)
| wissen | gewist
| Ik nodig mijn collega's uit. | Ik heb mijn collega's uitgenodigd.
| Ik haal mijn dochter (van de kinderopvang) op. | Ik heb mijn dochter opgehaald.
| Ik zet de oven aan/uit. | Ik heb de oven aangezet/uitgezet.
|===

=== presens vs perfectum vs imperfectum
* Ik werk al 6 jaar bij Bol.com (presens) - I have worked
* Ik heb 6 jaar bij Bol.com gewerkt. Nu werk ik bij ING. (perfectum) - I worked
* Ik werkte in China toen ik jonger was. (imperfectum)

== Zinnen Maken
=== Reflexieve werkwoorden
[cols="1,4"]
|===
| zich voorstelllen aan | Hij heeft zich voorgesteld aan Marit.
| zich voelen           | Voel je je niet zo goed? Ja, ik voel me me niet zo goed.
| zich interesseren     | Die interesseren me niet.
| zich aankleden        | Ik kleed me aan.
| zich herinneren       | Ik herinner me mijn pasword niet.
| zich vervelen         | Stefan verveelt zich een beetje.
| zich vergissen        | Je vergist je niet.
| zich voorbereiden op  | Wij bereiden ons voor op een wandelreis.
|===

<<<

== Onderwerpen
=== Normale dag
Wat doe je op een normale dag?

[cols="2,4",grid=none]
|===
| ontbijten                       | Ik ontbijten om half negen.
| eten                            | Ik eet eieren en een boterham.
| drinken                         | Ik drink een kopje melk.
| werken                          | Ik werk van half tien tot vijf uur.
| praten met collega's            | Ik praat met mijn collega's over programmeerproblemen, bugs, etc.
| hebben meetings                 | Wij hebben heel veel meetings.
| code schrijven                  | Ik schrijf code.
| code testen                     | Ik test geen code.
| e-mails schrijven               | Meestal schrijf ik e-mails in het Engels.
| e-mails lezen / checken         | Ik lees mijn e-mails na standup.
| pauze nemen                     | Ik neem elk uur pauze.
| koffie drinken                  | Je drinkt koffie.
| lunchen                         | Je luncht om half een.
| kletsen met collega's           | Je kletst met collega's.
Klets je met collega's?
| rijden                          | Hij rijdt auto.
| met mijn dochter spelen         | Wij spelen met onze dochter.
| mijn dochter verschonen         | Ik verschoon mijn dochter.
| mijn dochter wassen             | Mijn vrouw wast onze dochter.
| mijn dochter naar bed brengen   | Zij brengt mijn dochter naar bed.
| Netflix kijken                  | 's Avonds kijk ik Netflix.
| huiswerk maken                  | Ik maak Nederlands huiswerk.
| huizen bezichtigen              | We bezichtigen huizen.
|===

==== Normale zaterdag
- We gaan buiten spelen met onze dochter.
- Mijn dochter speelt in de speeltuin met andere jongens en meisjes.
- 's Morgens gaan we koffie drinken in een cafe in onze buurt.
- Soms gaan we lunchen in een Thais restaurant.
- Mijn vrouw videochat met haar ouders.
- We bezoeken vrienden.
- We gaan boodschappen doen met de fiets als het niet regent.
- We maken het huis schoon.
- Mijn dochter helpt me met het schoonmaken van de vloer.

=== Kletsen
|===
| Ik kom net uit een vergadering. | I just got out of a meeting.
| Ik heb vandaag heel veel vergaderingen. |
| Elke vergadering duurt heel lang. |
| Zijn ze saai of interessant? Allebei |
| Sommige zijn saai en sommige zijn interessant. |

| We blijven bijna het hele weekend thuis. |
| We zijn bijna het hele weekend thuis gebleven. |

| Ik ben jarig op 1 januari. |
| Ik ben geboren op 1 januari 1999. |
|===

=== "ga naar"
[cols=2]
|===
| met artikel (de, het)
| Ik ga naar de markt. +
Ik ga naar de ziekenhuis. +
Ik ga naar de kantine.

| zonder artikel (固定搭配)
| Ik ga naar huis. +
Ik ga naar kantoor. +
Ik ga naar bed. +
Ik ga naar school. +
Ik ga naar Nederlandse les.
|===

=== Lastige woorden
https://blogs.transparent.com/dutch/tackling-tricky-dutch-words/

==== Verstaan vs. Begrijpen
While both verstaan and begrijpen mean ‘to understand’, there is a difference in the context that they are used.

*Verstaan* is used when you are talking about something that you hear. If you can’t understand someone because they need to talk louder (harder) or more clearly (duidelijker), then you would use verstaan. It is also used when discussing understanding or knowing/being able to comprehend another language.

- Ik versta je niet. De radio staat aan! De verbinding is slecht!
- Sorry, ik versta u niet goed. Kunt u het nog een keer zeggen?
- Ik ben een beetje doof, ik versta u niet. (I am a little bit deaf, I don’t understand you.)
- Ik versta geen Arabisch. Dat heb ik op school nooit geleerd. (I don’t understand Arabic. I never learned that in school.)

*Begrijpen* is used when you are talking about actually understanding the meaning of something.

- Ik begrijp je niet. Kun je dat uitleggen?
- Ik ben niet doof, dus is versta u heel goed, maar ik begrijp u niet. U praat nonsens! (I am not deaf, so I understand [hear] you very good but I don’t understand you. You talk nonsense!)

==== Betekenen vs. Bedoelen
Betekenen and bedoelen both can be translated as ‘to mean’.

*Betekenen* is used in situations where something can be interpreted, more or less, the same by everyone (e.g. a traffic sign). Most particularly, beteken is used in relation to words.


- ‘Melk’ betekent ‘milk’, begrijpt u dat? (‘Melk’ means ‘milk’, do you understand that?)
- Dit symbool betekent ....
- Wat betekent dat Chinese karakter?
- Wat betekent zadel? Een zadel is een ding op je fiets. Je zit op het zadel.

*Bedoelen*, on the other hand, is more people related and used to reflect a certain intention someone has when stating or saying something.

- Wat bedoelt Marie? (What does Marie mean?)
- Ik bedoel....
- Wat bedoel je?

==== Weten vs. Kennen
Weten and kennen, both which mean ‘to know’ are one of the hardest pairs to explain and understand. So, don’t feel bad if you find this one challenging.

*Kennen* is used more often in relation to being aquainted with someone or something. Kennen is also a transitive verb, meaning it needs an object.

- Kent u meneer Ruisdaal? (Do you know Mr. Ruisdaal?)

*Weten* is used, usually, to refer to facts. It is often in sentences with sub-clauses.

- Ik weet waar het museum is. (I know where the museum is.)

== De weg vragen en wijzen
=== De weg vragen
- Mag ik u iets u vragen?
- Bent u hier bekend?
- Weet u waar ... is?
- Ik zoek ...

=== De weg wijzen

- Bij de stoplichten linksaf / rechtaf.
- Bij het kruispunt rechtdoor.
- Je staat met je rug naar station.
- Volg de weg / de bordjes.
- ... is aan je rechterhand / linkerhand.
- ... is aan de rechterkant / linkerkant.
- U gaat hier rechtdoor.
- U steekt de straat over.
- U gaat linksaf / rechtaf.
- Ann het eind van de straat gaat u linksaf / rechtaf.
- U neemt de eerste / tweede / derde straat rechts / links.
- U gaat de trap op naar boven.
- U gaat de trap af naar beneden.
- U gaat in die richting.

== Dit / Deze / Dat / Die

[cols=3]
|===
| | *Hier* | *Daar*
| de | Deze broek is goedkoop | Die broek is duur
| het | Dit boek is goedkoop | Dat boek is duur
| | *Hier* | *Daar*
|enkelvoud | Dit is mijn jas | Dat is jouw jas (enkelvoud)
| meervoud | Dit zijn  mijn broeken | Dat zijn jouw boeken
|===



<<<

== Huiswerk
=== Huiswerk 2023-11-10
==== vragen
- Al snel hadden we toen het plan om een jaar lang door Nederland te reizen om te zien of we hier ook avonturen konden beleven. (Wat is de hoofdzin?)
- We wilden eerst die verre landen bezoeken en darten niet aan Nederland. (die, verre)
- Door onze reizen wisten we dat het niet vanzelfsprekend is hoe het hier gaat en wat je allemaal ziet. (Betekenis)
- We gaan een paar weken weg is het wel leuk om zo lang door Nederland te zwerven? (Wanneer gebruik je wel)
- Helaas is er toen een onder de auto gekomen. (waarom toen)
- Maar tegenslagen zijn op zich niet erg (op zich) in it self, by itself
- check (?) below

==== p100 scheidbaar werkwoord

Ik zoek het telefoonnummer op.
Ik zocht  ... op.
Ik heb het telefoonnummer opgezocht.
Ik denk dat ik het telefoonnummer opzoek. (?)
Het is makkelijk om het telefoonnummer **op** te zoeken. (?)
Ik moet het telefoonnummer opzoeken.
Ik hoef geen telefoonnummer op te zoeken. (?)

Hij raakt de hond aan.
Hij raakte de hond aan.
Hij heeft de hond aangeraakt.
Hij zegt dat hij de hond aanraken.
Het is leuk om de hond aan te raken.
Hij mag de hond niet aanraken. (?)
Hij hoeft de hond niet aan te raken.

Wij brengen de vakantie in eigen land door.
Wij brachten de vakantie in eigen land door.
Wij hebben de vakantie in eigen land doorgebracht.
Wij denken dat wij de vakantie in eigen land doorbrengen.
Het is geen probleem om de vakantie in eigen land door te brengen.
Wij zullen de vakantie in eigen land doorbrengen.
Wij hoeven geen vakantie in eigen land door te brengen. (?)
Wij hoeven de vakantie niet in eigen land door te brengen. (?)

==== p104 Op24
1. De deur van mijn kamer stond open, daarom liep hij bij mij binnen.
2. Ahmad had te veel eten gemaakt, dus we hebben niet alles opgekregen.
3. Vandaag gaan we trouwen! Ik heb wel twee jaar naar deze dag uitgekeken.
4. Tina en Sam zijn vandaag langsgekomen, helaas was je niet thuis.
5. Heb je met oud en nieuw vuurwerk afgestoken?
6. Wat we gingen besluiten, [.line-through]#hingen# hing van het weer af.
7. We hebben straks een afspraak op Kerkplein 6. Heb jij opgezocht waar dat is?
8. Ze zei vroeger altijd dat we bij haar [.line-through]#uitscholden# terechtkonden als we problemen hadden.
9. Waar hebben jullie het weekend [.line-through]#terechtgekund# doorgebracht, in Groningen of in Amsterdam?
10. Sorry, u bent een week te laat, het congres heeft vorige week al plaatsgevonden.
11. Ik heb gehoord dat er een heel leuke band op dat feest optrad.
12. Hoe laat zijn jullie gisteren thuisgekomen? Het was na 24.00 uur.
13. Hebben jullie de honden al uitgelaten?
14. Werd jij als kind vroeger **uitgescholden**?

==== p105 op25
1. Tamara zei dat ik mijn telefoon niet mocht gebruiken. Ze verbood me dat.
2. Ze zijn samengekomen om fest te vieren.
3. Wie heeft dat leuke project bedacht?
4. Hij heeft de tekst uit zijn hoofd opgezegd.
5. Hoe laat begon het vuurwerk gisteren?
6. Wat fijn dat jullie die problemen hebben [.line-through]#overgewonnen# overwonnen.
7. Uit onderzoek is gebleken dat de meeste toeristen in Nederland hier een week blijven.
8. Wanneer heb je besloten om naar het buitenland te gaan?
9. Waar is die traditie uit voortgekomen?
10. Tijdens het feest kon niemand stilstaan, iedereen bewoog op de muziek.

=== Huiswerk 2024-01-19
_1. Maak 5 zinnen voor een gesprekje met een collega (over werk of weekend - kies zelf) Waar ligt het zinsaccent?_

- Hoe *gaat* het met jou?
- Het gaat *goed*.
- Wat heb je *gedaan* in het weekend?
- Op *zaterdag* gingen we naar *IKEA*. We hebben wat *meubels* gekocht. We kochten *een kast* voor de studiekamer en *twee stoelen* voor de eetkamer.
- Op *zondag* had my dochter een *speeldate* met haar vriendin. Dus we gingen *samen* naar de boerderij,

_2. p. 121 + woordenlijst p. 122/123 lezen (volgende les)_
hè hè

_3. oefenen met perfectum en imperfectum_
- wordwall imperfectum
- wordwall perfectum

_NOS Nieuws van de week- Kijk het nieuws, noteer nieuwe woorden en vertel over één onderwerp in de les_
wet
Door de nieuwe spreidingswet worden asielzoekers beter opgevangen en worden de opvangplekken eerlijker over het land verdeeld.


hebben te maken met bedreigingen en geweld
worden weggejaagd door
pakken hun klanten af
Rik maakte dat wel eens mee.
Links en rechts hoor ik daar natuurlijk wel wat over.
lopen ... rond
goed te merken
moet vergunning aanvragen

mees kees
#1
Er is een belangrijke nieuwe wet in Nederland.
In die wet staat hoe asielzoekers moeten worden opgevangen.
Op deze beelden is te zien hoe politici in de Eerste Kamer vóór die nieuwe wet stemmen.
Dit betekent dat het wetsvoorstel is aanvaard.
De nieuwe wet wordt de spreidingswet genoemd.
De wet regelt hoe asielzoekers worden verspreid over ons land.
Het gaat dan om het aantal opvangplekken per gemeente.
Gemeentes die uit zichzelf meedoen, krijgen geld om de asielzoekers een bed en eten te geven.
Gemeenten die niet meewerken kunnen door de nieuwe wet gedwongen worden...
...om asielzoekers op te vangen.
Het is een wet waar al lang over wordt gepraat.
Door de nieuwe regels moeten de problemen met asielzoekers...
...in Ter Apel worden opgelost.
En Ter Apel ligt hier.
Dit zijn oude beelden waarop is te zien dat asielzoekers in Ter Apel...
...buiten moesten slapen, omdat er nergens anders plek voor ze was.
Een asielzoeker vertelt hoe dat voelt.
Hulpverleners maken zich grote zorgen over deze situatie.
Want er wordt niet goed voor de asielzoekers gezorgd.
Mensen die in Ter Apel wonen merken ook dat er te weinig slaapplekken zijn.
Nou ja, als ze hier in de winkelwagens gaan slapen of in het park dat is niet fijn.
Je schrikt je rot als je een karretje wil pakken.
Sommige asielzoekers veroorzaken ook problemen.
Ze stelen bijvoorbeeld spullen uit de supermarkt en uit huizen.
Wij hebben ook de deur op slot. En camera's en alles.
Ik hoor ook dat heel veel mensen camera's aanschaffen.
Door de nieuwe spreidingswet worden asielzoekers beter opgevangen...
...en worden de opvangplekken eerlijker over het land verdeeld.
Er zijn 35000 extra plekken voor asielzoekers nodig in Nederland.
Vooral gemeentes in Noord-Brabant, Noord-Holland en ook Zuid-Holland...
...moeten door de nieuwe wet veel meer opvangplekken gaan regelen.
Zij vangen nu te weinig asielzoekers op, in vergelijking met andere provincies.
In de gemeente Gooise Meren, in Noord-Holland is dat, moeten ze...
...door de nieuwe wet waarschijnlijk meer dan 200 asielzoekers opvangen.
Inwoners vertellen wat ze daarvan vinden.
Ik denk dat als je in die situatie bent zoals deze mensen zijn...
...dan vind je het ook prettig als je een dak boven je hoofd hebt.
Ik denk dat het redelijk logisch is. Niet één gemeente kan alles gaan opvangen.
Ik vind het een heel moeilijk probleem -Waarom vindt u zo lastig?
Nou, omdat ik het ze wel gun. Maar ja, waar is de plek?
Ik heb een vriendin en die heeft een dochteren die kan geen huis vinden.
En dan denk ik, ja. Snapt u wat ik bedoel?
Op welke plekken de asielzoekerscentra precies komen, is nog niet duidelijk.
De wet geldt vanaf 1 februari.


#2
Glazenwassers in Nederland hebben te maken met bedreigingen en geweld.
Ze worden weggejaagd door andere glazenwassers.
Vaak gaat het om criminele bedrijven. Die bedrijven pakken hun klanten af.
Glazenwasser Rik maakte dat wel eens mee.
Toen werd ik eigenlijk gebeld door iemand die zei van: 'Hey, je bent in mijn wijk aan het werk.'
Terwijl dat was eigenlijk letterlijk de straat, de wijk, waar ik zelf woonde.
En dat was in eerste instantie gespeeld vriendelijk.
Van: 'Maar effe wegwezen hier vriend.'
En als je dan aangeeft dat je dat niet van plan bent, dan gaat het van kwaad tot erger.
De bedreiger van Rik is inmiddels opgepakt door de politie.
Maar er lopen nog veel criminele glazenwassers rond.
Vooral in de gemeente Zaanstad is dat goed te merken.
De burgemeester van Zaanstad legt uit hoe dat kan.
Wij zien dat vanuit Zaanstad ongeveer heel Nederland wordt bestierd...
...als het gaat om glazen wassen.
's Ochtends vroeg verzamelen ze zich op een aantal punten in wijken in Zaanstad.
Daar worden de werkbonnen verdeeld. En die rijden dan heel Nederland in.
En we hebben ook gezien en we krijgen ook reacties van collega's uit heel het land...
...dat zij ook te maken hebben met Zaanse glazenwassers en daar ook last van hebben.
Glazenwasser Leon werkt in de gemeente Zaanstad en kent de verhalen ook.
Ja, ze noemen het de glazenwassersoorlog.
Links en rechts hoor ik daar natuurlijk wel wat over.
- En wat hoort u dan precies? Ja met name de intimidaties.
Naar elkaar toe. Vechtpartijen, schietincidenten.
En het is ook heel erg bekend dat je in bepaalde steden word je gewoon van je ladder afgeschopt...
...als je aan het glazenwassen bent.
De burgemeester van Zaanstad wil de criminele glazenwassers aanpakken.
Hij bedacht daarom nieuwe regels.
Elke glazenwasser daar moet voortaan een vergunning aanvragen en wordt gecontroleerd.
Wat wij lokaal doen is een vergunningsplicht invoeren voor elke glazenwasser.
Dus dat betekent dat die 1100 glazenwassers vanaf 1 juli een vergunning moeten aanvragen...
...en die worden dan gescreend.
De burgemeester hoopt dat door de controles duidelijk wordt...
...welke glazenwassers geen eerlijk bedrijf hebben.
Die krijgen dan geen vergunning en mogen dan ook niet meer glazen wassen.

#3
Het gaat overal ter wereld slecht met de pinguïn.
De vogel leeft vooral in koude gebieden, zoals op de Zuidpool.
Door de opwarming van de aarde, smelt het ijs waarop ze leven.
Maar ook met pinguïns in warme gebieden gaat het niet goed.
Bijvoorbeeld in Zuid-Afrika. Daar leeft de Afrikaanse pinguïn.
Ooit waren er miljoenen Afrikaanse pinguïns. Nu zijn er minder dan tienduizend paartjes.
Deze natuurbeschermers tellen ze elke dag.
De natuurbeschermers zien dat de dieren zwakker worden.
De kans bestaat dat de Afrikaanse pinguïn over een aantal jaren is uitgestorven.
En dat komt doordat de dieren niet genoeg te eten hebben.
Onze correspondent legt dat uit.
Een van de redenen waarom het slecht gaat met de Afrikaanse pinguïn...
...is omdat ze honger hebben.
Dit is hun voornaamste eten: het sardientje....
...maar daar zwemmen er steeds minder van in de zee.
Er zijn steeds minder sardientjes in de zee, omdat mensen ze ook lekker vinden...
...en erop vissen.
Een natuurbeschermer vertelt daarover.
In Zuid-Afrika zijn daarom nieuwe regels gemaakt voor vissers.
In sommige gebieden mag de komende tien jaar niet meer worden gevist op sardientjes.
Vissers zijn daar niet blij mee. Maar volgens onderzoekers moet er juist meer gebeuren.
De kans dat dat lukt is niet zo groot.
Intussen proberen natuurbeschermers zoveel mogelijk zwakke pinguïns te redden.
Die worden dan naar een opvangplek gebracht.
Daar krijgen ze sardientjes uit de vriezer.
En kunnen ze weer sterker worden.
Samenvatting van de uitzending.
In dit journaal vertelden we dat asielzoekers meer over het land verspreid gaan worden.
Dat glazenwassers steeds vaker worden weggejaagd of bedreigd zelfs door criminelen.
En dat er zorgen zijn over de Afrikaanse pinguïn. De soort dreigt uit te sterven.
Dit was het voor nu.
Volgende week is er weer een journaal van de NOS in makkelijke taal.

notities 2024-01-26

Ik ben eindelijk gedaan.
Ik ben eindelijk klaar
Ik wil het volhouden.


Huiswerk 2024-01-26
Opdracht 21 Preposities (hoofdstuk 3 en 4)

1. Hij baalt *van* het warme weer.
2. Ben je weleens *in* je eentje op vakantie geweest?
      #Vraag:  in je eentje
3. Hij heeft twee uur [.line-through]#in# #op#  de trein gewacht.
4. We gaan dit weekend *met* z'n tienen naar Brussel: vijf vrienden en hun partners.
      #Vraag: z'n
5. Ze vertelt altijd heel veel over haar leven, maar ze informeert nooit [.line-through]#aan# #naar# mijn leven.
6. Ik mis onze kat heel erg. Als ik weer in Kroatië ben, ga ik eest lang [.line-through]#naar# #met# mijn kat knuffelen.
7. Het is een drukke week, ik kijk [.line-through]#voor# #naar# het weekend uit.
      #Vraag: uitkijken naar
8. We eindigen onze reis *met* een overnachting in een heel luxe hotel.
9. Ik vind het leuk dat onze feesten voortkomen [.line-through]#door# #uit# dezelfde lengende.
      #Note: voortkomen uit - derive from, originate from
10. We willen graag een jaar op reis, maar het ontbreekt ons [.line-through]#van# #aan# geld, dus we gaan korter.
      #note: why?
11. We genieten altijd heel erg  [.line-through]#door# #van# onze vakanties, we maken altijd prachtige reizen.
12. Toen we op de Marker Wadden waren, konden we nergens schuilen [.line-through]#van# #voor# de regen.
13. Toen ik net in Nederland was, had ik enorme heimwee [.line-through]#voor# #naar# mijn eigen land.
14. In onze vakantie gaan we [.line-through]#naar# #door# het noorden van Spanje trekken.


Nieuws

#1
regering

#2
aardbeving
ramp
storten in
overleefden de aardbeving niet

=== Huiswerk 9/2

1. Wat was je favoriete vak op school?
Mijn favoriete vak was gym, want ik hou van sport.

2. Je moet kiezen: onderwijs geven of onderzoek doen. Wat kies je?
Onderzoek doen. Ik kan iets interessants kiezen.

3. Aan welk vak op school had je een hekel?
Ik had een hekel aan Chinees.

4. Wie was je favoriete docent? Waarom?
Mijn favoriete docent was de hoofdleraar van mijn groep. Hij is een interessant mens. Hij vertelde ons veel verhalen over de geschiedenis die niet uit het leerboek komen

5. Wat zou je graag willen onderzoeken?
Ik zal graag houtbewerking willen onderzoeken.

6. Heb je op school een uniform gedragen? Zo ja, hoe zag het eruit? Zo nee, vind je dat jammer?
Ja, ik op school een uniform gedragen. We hadden twee soorten uniformen, een voor sport en een voor dagelijks gebruik.

7. Welk vak heb je gemist op school?
Ik heb de geschiedenis gemist.

8. Wat zou je nog eens willen leren?
Ik zal de scheikunde nog eens willen leren.

9. Het is belangrijk om een beetje stress te hebben, volgens de tekst. Wat vind jij?
Ik vind het ook. Het kost me veel tijs als ik geen stress heb.

=== NOS Nieuws

Dit is het Nieuws van de Week, een journaal van de NOS in makkelijke taal.
En ik ben Saida Maggé.
In dit journaal gaat het over gevechtsvliegtuigen.
Nederland mag geen onderdelen voor dit soort vliegtuigen meer naar Israël sturen.
Dat heeft te maken met de oorlog in Gaza.
We laten mensen horen die bij de brandweer werken.
Zij vinden dat er te weinig aandacht is voor de nare dingen die ze meemaken tijdens hun werk.
En we laten zien hoe jongeren een jaar bij het leger werken om te kijken of het iets voor ze is.

#1
Nederland mag geen *onderdelen* voor *straaljagers* meer leveren aan Israël. Dat heeft te maken met de oorlog in Gaza. De straaljagers worden gebruikt in die oorlog. Hulporganisaties hadden een rechtbank gevraagd om de levering te verbieden.
We beginnen met nieuws over *gevechtsvliegtuigen*.
Nederland mag geen onderdelen meer leveren aan Israël voor dit soort vliegtuigen.
Dat is *besloten* in een *rechtszaak*.
Het gaat om een bepaald type straaljager, de F-35.
Hij kan worden gebruikt voor bijvoorbeeld bombardementen.
Onderdelen van de straaljager liggen in Nederland opgeslagen.
Dat gebeurt hier, in Woensdrecht.
Op deze plek worden ook motoren van de F-35 gerepareerd.
Vanuit Woensdrecht gaan die spullen naar landen die F-35 toestellen gebruiken.
Israël is één van die landen.
Het Israëlische leger gebruikt de straaljagers de laatste maanden om Gaza vanuit de lucht aan te vallen.
Ze zeggen dat dat nodig is om Hamas uit te *schakelen*.
Dat is een terroristische organisatie uit Gaza.
Maar door zulke bombardementen zijn ook vele duizenden inwoners van Gaza om het leven gekomen.
Nederlandse hulporganisaties *maken zich zorgen over* de bombardementen en over de *gevolgen* voor de inwoners van Gaza.
Ze stapten naar de rechter.
Ze willen dat Nederland stopt met het leveren van F-35 onderdelen aan Israël.
In de rechtbank hebben ze nu gelijk gekregen.
Nederland mag de onderdelen niet meer naar Israël sturen.
De rechtbank denkt dat door de straaljagers ook onschuldige mensen om het leven kunnen komen.
Dat vertelt een vrouw van de rechtbank.
Die onderdelen dat zijn militaire *goederen* en die mag je niet zomaar leveren aan andere landen.
Daar zijn regels voor. Nationale regels en internationale regels.
De hulporganisaties zijn blij om dat te horen.
Maar ze vinden het jammer dat er een rechtszaak voor nodig was.
Dat is gewoon een ontzettend belangrijke uitspraak.
Het is ook wel moeilijk vind ik dat we daar maandenlang voor hebben moeten knokken.
Terwijl iedereen natuurlijk al lang kon zien wat er hier aan de hand was.
Maar goed, vandaag telt dat deze uitspraak staat en daar ben ik heel blij mee.
De Nederlandse regering is het niet eens met het besluit van de rechtbank.
Ze denkt dat Israël de onderdelen nodig heeft zodat het land zich kan verdedigen...
...tegen terroristen.
De regering wil daarom dat een hogere rechter opnieuw naar het besluit kijkt.

#2
Mensen die bij de brandweer werken *maken soms heftige dingen mee*. Sommigen *blijven daar aan denken* en krijgen allerlei *klachten*. Zij willen meer hulp bij die klachten. Volgens hen is daar niet genoeg aandacht voor bij de brandweer.
Mensen die bij de brandweer werken, maken vaak heftige dingen mee.
Ze kunnen daar last van krijgen.
Onderzoekers vinden dat daar meer *aandacht* voor moet komen.
Brandweermensen hebben te maken met heftige *gebeurtenissen* waarbij ze anderen moeten helpen.
Niet alleen bij brand maar ook bij andere nare dingen.
Dat vertelt een vrouw die bij de brandweer werkte.
Verkeersongevallen, zelfdodingen, reanimaties, ja die hakken er wel in.
Sommige brandweermensen kunnen de dag erna gewoon weer naar hun werk.
Maar anderen blijven denken aan wat ze hebben meegemaakt en worden ziek. Zij hebben PTSS.
Ze kunnen zich niet concentreren, ze kunnen niet goed slapen en ze worden schrikachtig.
Mensen die dit hebben kunnen hun werk niet meer goed doen. En ze hebben hulp nodig.
Maar bij veel *brandweerkazernes* worden ze op dit moment niet goed geholpen.
Michael kreeg PTSS door zijn werk bij de brandweer.
*Hij wist niet hoe hij ermee om moest gaan.*
De eerste reanimatie weet ik nog, eerste kinderreanimatie, eerste geweldsreanimatie die weet ik allemaal nog. En ga dat maar eens proberen te verwerken.
Martine heeft er ook last van en vond het moeilijk om erover te praten...
...met haar baas en haar collega's.
Op het moment dat je je zwaktes laat zien dan ben je er gewoon geweest.
Dan word je de pispaal, heb je geen leven meer bij de brandweer.
Uiteindelijk kwamen ze thuis te zitten.
Ze kregen steeds minder geld van hun baas en ze kregen geen hulp om beter te worden.
Dat moesten ze zelf regelen, terwijl ze erg ziek waren.
Dat vinden ze niet eerlijk.
Mensen met andere beroepen, zoals politieagenten en ambulancepersoneel...
...worden wel in de gaten gehouden. Als zij klachten hebben, krijgen ze hulp.
Bij de brandweer gebeurt dat vaak niet.
Er is daar ook niet bekend hoeveel medewerkers PTSS hebben.
Michael hoopt dat er meer aandacht voor het probleem komt.
Zodat collega's beter geholpen worden als ze klachten hebben.
Voor hem zelf is het te laat.
Hij denkt dat hij te ziek is om ooit nog bij de brandweer te werken.
-Ga jij nog terug naar de brandweer? Nee.

#3
Jongeren kunnen een jaartje meetrainen met het Nederlandse leger. Zo kunnen ze kijken of het werk iets voor ze is. Defensie hoopt dat ze na dat jaar blijven want er is een groot tekort aan personeel.
Het Nederlandse leger heeft last van een enorm personeelstekort.
In totaal zijn er 9000 nieuwe mensen nodig.
Daarom kunnen jongeren nu een jaar uitproberen hoe het is om bij Defensie te werken.
Dat heet een dienjaar.
Militairen die bij Defensie werken kunnen kiezen voor de landmacht...
...de luchtmacht, de marine of de marechaussee.
Ze doen meer dan alleen vechten in een oorlog.
Ze helpen bijvoorbeeld ook bij rampen zoals natuurbranden en overstromingen.
Afgelopen september begon het eerste dienjaar voor jongeren.
De jongeren kunnen het bijvoorbeeld doen na hun middelbare school.
Ze worden getraind en krijgen ook betaald.
Militair Erik legt dat uit.
Eigenlijk is het dienjaar een zinvolle manier om je tussenjaar in te vullen bij Defensie.
En het is een jaar een laagdrempelige militaire experience.
In dat jaar worden mensen opgeleid tot militair.
En worden ze, verdeeld over heel Defensie, voor de overige tijd ingezet.
En dat kan bij de landmacht, bij de marine, bij de luchtmacht of de marechaussee.
Esther doet mee aan het dienjaar en vertelt erover.
Je leert de theorie: rangen en standen. Je leert ook met een wapen omgaan.
Uiteindelijk ga je ook schieten op een schietbaan.
Ik wil gewoon zelf veel van de wereld zien maar ondertussen ook heel graag mensen helpen.
En dat kan heel goed bij Defensie.
Door de oorlogen in Gaza en Oekraïne is het erg onrustig in de wereld.
Daarom vindt Defensie het nodig dat meer mensen militair worden, vertelt Erik.
Het zal je niet ontgaan zijn dat Defensie ontzettend veel vacatures heeft.
Tegelijkertijd zie je dat de urgentie toeneemt, vanwege de situatie in de wereld.
En dit is eigenlijk een vorm waarop mensen het kunnen uitproberen.
Want Defensie is ook voor heel veel mensen een *ver-van-hun-bed-show*.
Heel veel mensen hebben helemaal geen feeling bij wat Defensie echt is.
En hiermee kunnen ze daadwerkelijk ervaren of het wat voor ze is.
En op basis daarvan kiezen of ze verdergaan binnen Defensie.
130 jongeren doen op dit moment mee aan de opleiding.
Defensie hoopt dat ze daarna bij het leger willen blijven.
Maar als ze dat niet willen, leren ze volgens Erik toch een hoop belangrijke dingen.
Je leert natuurlijk samenwerken, dat zien we ook wel achter ons.
Je leert onderdeel zijn van een team. Maar je wordt ook een stukje volwassener.
De vaardigheden die je hier meeneemt, daar ga je je hele leven plezier van hebben.
En dat zijn typisch ook dingen waar heel veel werkgevers om staan te springen.
Een groot deel van de jongeren heeft al gezegd te willen blijven bij Defensie.
Zoals Sam. Hij wil graag bij de luchtmacht.
Eerst ga ik het dienjaar afmaken en oriënteren.
En hopelijk dat ik dan kan tekenen. En natuurlijk het liefst officier-vlieger.

Samenvatting van de uitzending.
In dit journaal legden we uit waarom er een rechtszaak was over straaljagers.
Brandweermensen vertelden dat ze weinig hulp krijgen als ze iets naars meemaken.
En we lieten zien dat jongeren een jaar kunnen meetrainen bij het leger.
Dit was het voor nu.
Volgende week is er weer een nieuw journaal van de NOS in makkelijke taal.

=== Huiswerk 16/2
Opdracht 21 Onregelmatige werkwoorden

1. Gisteren waaide
2. gedropen
3. geschuild
4. kroop
5. 


=== Les 1 (25/10/2021)
==== Vraagwoorden (Nederlands in gang p.37 - h2 - opdracht 3)
[cols=2,grid=none]
|===
| 1  *Hoe* heet jouw zus?                      | Mijn zus heet Sandra
| 2  *Wat* doe je vandaag?                     | Ik ga naar de cursus.
| 3  *Waar* woont Astrid?                      | Astrid woont in de Brugstraat.
| 4  *Welke* cursus doe je?                    | Ik doe nu cursus 1.
| 5  *Wie* heeft mijn boek?                    | Ik. Ik heb jouw boek.
| 6  *Hoe* laat is het?                        | Het is nu tien voor twee.
| 7  *Waar* zijn de docenten?                  | De docenten zijn in de kantine.
| 8  *Wie* komen uit Australie?                | Peter en Aice komen uit Australie.
| 9  *Waar* komt Patrick vandaan?              | Patrick komt uit Maastricht.
| 10 *Welke* dag is het?                       | Het is vandaag maandag.
| 11 Over *welke* vakantie vertelt Jeroen?     | Hij vertelt over zijn zomervakantie.
| 12 Met *wie* zit je in de kantine?           | Ik zit met Petra in de kantine.
| 13 *Waarom* is je broer in China?            | Hij is daar voor zijn werk.
| 14 *Hoeveel* zussen heb je?                  | Ik heb twee zussen.
|===

==== Possessief pronomen (Nederlands in gang p.38 - h2 - opdracht 4)

. Wij wonen nu in Zwolle. *Ons* adres is Rozenstraat 8.
. Ik woon in Amersfoort en *mijn* zus woont in Rotterdam.
. Mevrouw Jansen, gaat u met *uw* broer op vakantie?
. Vera en Hilda, vertellen jullie eens over *jullie* vakantie.
. Dit is Farah en *haar* achternaam is Ahmany.
. Herman, de docent, spreekt met *zijn* buurman over de cursus.
. Wij komen uit polen en *onze* cursus begint maandag.
. Edit en Ning zitten met *hun* docent in de kantine.
. Theresa, woont *je* familie ook in Nederland?
. Peter moet voor *zijn* werk naar Indonesie.

==== Maanden en seizoenen (Nederlands in gang p.41 - h2 - opdracht 10)

Vul in: *op*, *om* of *in*

. De cursus begint *op* maandag 8 april, *om* 9.00 uur.
. Heb jij ook les *op* dinsdag?
. De tweede cursus begint *in* januari.
. We zijn *om* 9.45 uur in Amsterdam.
. Fred is *op* 12 augustus jarig.
. Ben jij ook *in* de zomer jarig?
. Bart en Eva zijn *in* 2017 getrouwd.
. *Op* welke datum zijn ze getrouwd?
. Ze zijn *op* 7 juli getrouwd.
. We gaan *om* 10.30 uur naar de kantine.
. Gerard en Senna gaan *in* oktober op vakantie.
. Hij is *op* 23 mei 1991 geboren.


=== Les 2 (01/11/2021)
==== Hoofdzin met inversie (Nederlands in gang p.52 - h3 - opdracht 6)
[cols=2]
|===
| 1. Joyce is donderdag jarig. | Donderdag is Joyce jarig.
| 2. We drinken koffie in de kantine. | In de kantine drinken we koffie.
| 3. Ze zjin op het moment in Indonesië. | Op het moment zijn ze in Indonesië.
| 4. Ik weet dat niet. | Dat weet ik niet.
| 5. Ze wonen in de winter in Barcelona. | In de winter wonen ze in Barcelona.
|===

==== Modale werkwoorden (Nederlands in gang p.90 - h6 - opdracht 4)
Welk werkwoord is logisch in de zin?

. Wat *zullen* we drinken? Wijn?
. Mijn ouders *kunnen* niet op mijn verjaardag komen.
. Hans *wil* een jaar in Canada wonen.
. Aan mijn tafel *kunnen* vier personen zitten.
. Jullie *moeten* deze opdracht maken.
. Jullie *mogen* samenwerken.
. Ik ben jarig. Ik *wil* een rondje geven.
. *Mag* ik u iets vragen?
. *Zal* ik morgen om half negen komen?
. *Kunnen* veel Nderlanders Engels spreken?

==== Modale werkwoorden (Nederlands in gang p.90 - h6 - opdracht 5)

Vul een vorm in van *mogen*, *willen*, *moeten*, *kunnen* of *zullen*.
Wat is logisch?

. *Wil* je in dit cafe ook iets eten?
. Je *moet* deze soep eens proeven. Heerlijk!
. Je *kan* ook alleen een voorgerecht nemen. Dat is goed.
. Ik houd van vis. Ik *wil* de paella.
. *Kan* je nu al Nederlands spreken? Wat goed!
. Mijn achternaam is Alasadi. *Zal* ik het even spellen?
. *Mag* ik twee koffie en een glas water alstublieft?
. Jonas is zestien jaar. *Mag* hij bier bestellen in een café?

=== Les 3
==== Perfectum (Nederlands in gang p.132 - h9 - opdracht 5)
Vul het participium in van het werkwoord tussen haakjes.

. Heb je gisteren een wedstrijdje *gespeeld*?
. Hij heeft zijn docent een prettig weekend *gewenst*.
. Ze is met de cursus *gestopt*.
. Heb je de mosterdsoep *geproefd*.
. De serveerster heeft een lepel *gehaald*. (spreek 'd' uit als 't')
. Heeft de heer Smit aan de bultjes *gekrabd*. (spreek 'd' uit als 't')
. Heeft je zus in New York *gewoond*.
. Ik heb mijn familie veel over de cursus Nederlands *verteld*. (vertel-len -> vertel -> verteld)
. Heb je gisteren het bad *gebruikt*?
. We heeft de koffie *betaald*.

==== Zinnen maken
Maak een zin in het perfectum met: fietsen, wonen, stoppen, huren, maken

. Ik ben vorig weekend met mijn dochter en mijn vrouw naar de supermarkt *gefietst*.
. Vijf jaar geleden *hebben* we in Hilversum *gewoond*.
. Hij is met Nederlands leren *gestopt*.
. Zijn hebben een appartement *gehuurd*.
. Vorige week heeft mijn buurman heel veel lawaai *gemaakt*.
. Vorige week heeft mijn buurman overdag heel veel lawaai *gemaakt*.

==== Normale werkdag op kantoor
Schrijf een korte tekst over een normale werkdag op kantoor. Wat doe je?

. Ik ga een dag per week naar kantoor.
. Ik ga met de auto naar kantoor.
. Ik kom om *ongeveer* half tien *op kantoor* aan.
. Ik *haal* een koffee op AH to-go.
. Ik ga met lift naar mijn werkplaats.
. Om 9.45 hebben we de stand-up. (hebben of doen)
. *Tijdens* de stand-up vertelt iedereen iets over zijn werk.
. We hebben veel vergaderingen.
. Om 12 uur ga ik met collega's lunchten.
. We hebben een uur lunchpauze.
. Ik schrijf code.
. Ik bekijk *ook* code. (ook moet na werkwoorden)
. Soms speel ik met mijn collega's bordspellen. (bordspellen met collega's?)
. Meestal ga ik om 5 uur naar huis.
. Onderweg naar huis haal ik mijn dochter op.

=== Les 4
==== Selecteer het perfectum en schrijf de infinitief
Mijn weekend

Je wil vast wel weten wat ik dit weekend heb gedaan (doen), want ik heb een heel leuk weekend gehad (hebben)!

Op vrijdagavond heb ik samen met mijn huisgenoot gekookt. Hij heet Willem. Na het eten hebben we een spannende film gekeken (kijken). Willem is na de film naar bed gegaan (gaan), maar ik ben nog opgebleven (opblijven). Ik heb een paar pagina’s van mijn boek gelezen (lezen).

Op zaterdagochtend ben ik om half acht opgestaan (opstaan). Dat is best vroeg voor een zaterdagochtend! Eerst heb ik uitgebreid ontbeten (ontbijten) en daarna heb ik de fiets uit de schuur gehaald(halen). Ik ben naar de supermarkt gefietst. Ik heb appels, eieren, boter en meel gekocht (kopen). Daarna ben ik weer op de fiets gesprongen (springen). Op weg naar huis heb ik een bosje bloemen gehaald (halen) bij de bloemenkraam. Ik hou van bloemen.


Toen ik weer thuis was, heb ik de bloemen in de vaas gezet (zetten) en ik heb de oven aangezet (aanzetten). Daarna heb ik de appels geschild (schillen) en gesneden (snijden). Vervolgens heb ik het meel, de eieren en de boter gemixt (mixen). En weet je wat ik heb gemaakt (maken)? Je kunt het wel raden: een appeltaart! Hij is heel goed gelukt (lukken)! Ik heb de taart aan Willem gegeven (geven). Hij is vorige week namelijk jarig geweest (zijn). De taart was erg lekker. Ik heb zelf ook een flink stuk genomen (nemen).

Op zaterdagmiddag heb ik mijn oma gebeld (bellen). Ze heeft me verteld dat ze veel in de tuin heeft gewerkt (werken). Ik bezoek mijn oma niet vaak. Ze woont erg ver weg. Vorige maand heb ik haar één keer bezocht (bezoeken). Gelukkig kunnen we elkaar regelmatig bellen.

In de namiddag heb ik even in het park gewandeld (wandelen). Om zes uur ben ik terug naar huis gegaan (gaan). Ik ben onder de douche gesprongen (springen) en ik heb me omgekleed (omkleden). Ik heb mijn pyjama aangetrokken (aantrekken). De rest van de avond hebben Willem en ik bordspelletjes gespeeld (spelen). Het was erg gezellig! Ik heb twee keer gewonnen (winnen) en één keer verloren (verliezen). Daarna ben ik naar bed gegaan (gaan). Ik heb heerlijk geslapen (slapen).

Zondag was de beste dag van het weekend. Weet je wat Willem en ik hebben gekocht (kopen)? Een hondje! Het is een labrador. We hebben hem op een boerderij opgehaald (ophalen). Daar had een hond zes puppy’s gekregen (krijgen). Onze pup is heel lief. Hij heeft een mooie bruine vacht. Ik heb nog nooit eerder een huisdier gehad (hebben). We zullen heel goed voor hem zorgen. En weet je hoe we hem hebben genoemd (noemen)? Dali! Hij is vernoemd (vernoemen) naar die beroemde Spaanse kunstenaar.
En jij? Wat heb jij dit weekend gedaan (doen)?

==== Opdracht 5 (Nederlands in gang p.133)
Vul het participium in van het werkwoord tussen haakjes. (onregelmatige werkwoorden)

. Ik heb gisteren op de markt boodschappen *gedaan*.
. Mijn zus heeft op haar verjaardag een camera *gekregen*.
. Wij zijn een halfjaar geleden naar Nederland *gekomen*.
. Heb je gisteren naar die serie *gekeken*?
. De makelaar heeft ons heel goed *geholpen*.
. De serveerster heeft hem een kopje koffie *gegeven*.
. Ben je zaterdag of zondag naar Amsterdam *gegaan*?
. Ik ben in het weekend ziek *geweest*.
. Mijn vriend is gisteren bij zijn ouders *gebleven*.
. Heb jij onze docent *gezien*?

==== Opdracht 6 (Nederlands in gang p.133)

Regelmatige werkwoorden

. Wie heb je gisteren gebeld? Gisteren heb ik mijn ouders gebeld.
. Waar heb je gewoond? Ik heb in Eindhoven gewoond.
. Ben je met de cursus Nederlands gestopt? Ja, ik ben met de cursus Nederlands verder gegaan. (?)door gegaan
. Wat heb je in een cafe in het Nederlands besteld? I heb een latte besteld.
. Heb je een gemeubileerde kamer gehuurd? Nee, ik heb geen gemeubileerde kamer gehuurd.
. Waar heb je vorig jaar gewerkt / gestudeerd? Ik heb vorig jaar thuis gewerkt.
. Wanneer heb je naar de dialoog van hoofdstuk 9 geluisterd? Ik heb vorig weekend naar de dialoog van hoofdstuk 9 geluisterd.
. Wat heb je deze week betaald? Ik heb deze week de boete voor te hard rijden betaald.
. Wie heb je getrakteerd? Ik heb mijn collega's getrakteerd.
. Wat heb je geruild? Ik heb niks geruild.

Onregelmatige werkwoorden

. Wanneer is de cursus begonnen? De cursus is om 15.00 uur begonnen.
. Waar ben je dit jaar op vakantie geweest? Dit jaar ben ik op vakantie in Soest geweest.
. Wat heb je vandaag gedronken? Ik heb vandaag twee kopjes koffie gedronken.
. Wat heb je gisteren gegeten? Ik heb gisteren chinese hotpot gegeten.
. Wie heb je vorige week een e-mail geschreven? Ik heb vorige week een e-mail aan mijn ouders geschreven.
. Hoe laat ben je gisteren naar huis gegaan? Ik ben gisteren om 6.00 uur naar huis gegaan.
. Heb je vorige maand last van je keel gehad? Ja, ik heb vorige maand last van mijn keel gehad.
. Wanneer ben je naar Nederland gekomen? Ik ben in 2009 naar Nederland gekomen.
. Wat heb je op de markt gekocht? Ik heb een pak Kibbeling op de markt gekocht.
. Wat heb je voor je verjaardag gekregen? Ik heb een Nintendo switch van mijn vrouw voor mijn verjaardag gekregen.

==== Opdracht 7 (Nederlands in gang p.134)
Vul een vorm in ven *hebben* of *zijn*.

. Gisteren *heeft* mijn collega tot 01.00 uur gewerkt.
. Na de les *hebben* we een biertje gedronken.
. Wat *heb* he gisteren gedaan?
. Simon *heeft* de badkamer niet gebruikt.
. Hoe laat *zijn* jullie met de les begonnen?
. Joana *is* dit jaar op vakantie in Portugal geweest. (uitspraak van e en ee)
. Onze buren *hebben* een nieuw huis gekocht.
. Waar *heb* je het boek besteld?
. Ik *ben* in het weekend thuisgebleven.
. *Hebben* jullie het huis gemeubileerd gehuurd?
. Hoe *heeft* Karen naar de les gekomen?
. Veronika en Victor *zijn* met de cursus gestopt.
. Brian *is* gisteren 36 geworden.
. *Bent* u met de bus gekomen?
. Sebastian en ik *zijn* om 11.00 uur naar de makelaar gegaan.
. We *hebben* in dat restaurant heerlijk gegeten.
. Waarom *ben* je die spijkerbroek geruild?
. *Zijn* jullie met Simona naar de dokter gegaan?
. Felix *heeft* vier uur met zijn vriendin in Zweden gebeld.
. *Heeft* de heer Smit last van de jeuk gehad?

=== Les 5
==== Vertel in de les over je weekend. Maak ministens 8 zinnen in het perfectum.
. Ik heb een nieuwe camera gezocht.
. Ik heb foto's van mijn dochter en vrouw buiten gemaakt. (how to say some photos? or you don't say this in Dutch)
. We hebben blauwe bessen en appels op de markt gekocht, want het fruit van/op de markt is meestal verser en goedkoper.
. Ik heb mijn ouders gebeld.
. We hebben het huis schoongemaakt.
. Ik heb het huiswerk van mijn Nederlandse les gedaan.
. Ik heb een paar boeken aan mijn dochter voorgelezen.
. In het weekend is mijn vrouw ziek geweest.
. We zijn naar de markt gefietst. (zijn?)

==== Een normale dag van je dochter
. Om 7:30 staat Emmie op.
. Mijn vrouw wast haar en kleedt haar aan.
. Zij ontbijt om 8:15 uur. (kwaalt alllen )
. Voor 9.00 uur brengen we Emmie naar de kinderopvang.
. 's Morgens speelt Emmie met haar docenten en vrienden.
. Om 12.00 uur luncht zij.
. Zij slaapt om 13.00 uur. (Wat is de Nederlands van "nap")
. 16.00 uur is de tijtussentdoortjestijd.
. We halen haar om 17.30 uur op.
. Daarna spelen we even samen.

==== Comparatief en superlatief Opdracht 6 p. 102
. Vind je rood *mooier* dan blauw?
. Is les 6 *leuker* dan les 7?
. Vind je paela *lekker*?
. Welke cursist is *het vaakst* in de les? (Wat is de betekenen van deze zin?)
. Welke spijkerbroek is *het goedkoopst*.
. Zijn de tomaten op de markt *roder* dan in de winkel?
. Vind je een laag model *prettiger* dan een hoog model?
. Is de cappuccino *het duurst*?
. Spreek je *beter* Engels dan Nederlands?
. Houd je *meer* van groente dan van fruit? (houtje)

==== Comparatief en superlatief Opdracht 7 p. 103
. Ik eet leiver spaghetti carbonara liever dan stamppot andijvie.
. Een kilo kip kost minder dan een kilo tomaten. (nee)
. Ik ben kleiner dan mijn docent. (nee)
. Ik vind thee lekkerer dan koffie.
. Juli is langer dan juni.
. Kleding in Nederland is duurder dan in mijn eigen land.
. Ik vind de film, Coco, het best.
. Ik weet het niet, maar ik moet het minst hebben. (moet ik of ik moet na de "maar")
. Den haag is de mooiste Nederlandse stad.
. Rusland is het grootste land.
. Vaticaanstad is het kleinste land.
. Thailand is het liefste land op vakantie.  Ik ga het liefst naar Thailand op vakantie.
. Ik vind de spreelpefeningen het leukst.
. Ik vind de uitspraak het belangrijkst bij het leren van een taal.

=== Les 6
==== Begrijpen en verstaan (p.145 opdracht 2)
. Sorry, er zijn hier veel mensen. Ik *versta* je niet goed. Wat zeg je? Kun je dat *nog een keer* zeggen?
. Kun je dat even *herhalen*?
. Wat *bedoel* / *zeg* je?
. Wat *betekent* dat?
. Hoe *zegt je dat* / *heet dat* in het Nederlands?
. Proost. *Zeg je dat zo* in het Nederlands?

==== Bedoelen en betekenen (p.146 opdracht 3)
. De buurman zei iets, maar ik wist niet wat hij *bedoelde*. (imperfectum)
. Hij is allergisch. Dat *betekent* dat hij geen tomaten mag eten.
. Ik neem een bakje champignons. Wat *betekent* 'bakje' eigenlijk?
. Mag ik dat groene, eh, daar, dat groene ...? O, u *bedoelt* peterselie.
. Wat *betekent* p.p.? Per persoon.

==== Fietsonderdelen (p.147 opdracht 4)
. de bagagedrager
. de band
. de bel
. de trapper
. het stuur
. het wiel
. het zadel
. de rem
. het achterlicht
. het voorlicht
. het slot
. de standaard

==== Imperfectum (p.149 opdracht 8)
// Regelmatige werkwoorden
. Hij *voelde* zich niet zo goed.
. Hans en Paul *stopten* na twee maanden al met hun studie.
. Ik *vierde* mijn verjaardag altijd met mijn familie.
. Alberto *bedankte* ons voor de leuke dag.
. *Woonden* jullie vroeger ook in een stad?
. Eerst *vertelde* hij over zijn reis naar Kenia.
. In Parijs *werkte* hij in een groot cafe.
. Het *regende* de hele week!
. Hij *miste* zijn ouders en zijn zusje.
. De kinderen *fietsten* elke dag naar school.
// Onregelmatige werkwoorden
. Tom *vroeg* iets aan zijn buurvrouw.
. Dat *wist* ik niet.
. Waar *stond* je fiets? Bij het restaurant?
. Ik *sliep* al heel lang zo slecht.
. Wesley *vond* de aardbeien heerlijk.
. Hij *zei* niets over onze afspraak.
. *Zagen* jullie mij niet?
. John en Marga *keken* naar de wedstrijd.
. Julia *dronk* thee met suiker.
. We *kwamen* te laat in de les.

==== Spreekopdracht voorbereiden: zoek een huis op Funda. Vertel iets over dit huis. Bijvoorbeeld:
- hoe groot is het?

- hoeveel verdiepingen heeft het huis?
- is er een tuin?
- Wat vind je mooi/niet mooi?
- is het groter/kleiner/mooier/minder mooi/ ... dan je eigen huis?

=== Les 7 （06/12/2021）
==== Imperfectum (Opdrach 9 p.150)
Werk in tweetallen. Beantwoord de vragen.

. Welke talen konden jullie vroeger leren op school? +
  We konden vroeger alleen Engels leren op school.

. Mocht jij met 16 jaar alleen op vakantie? +
  Nee, ik mocht met 18 jaar alleen o vakantie.

. Wat wilde jij worden als kind? +
  Ik wilde een dokter worden als kind. (how to say I don't know what I wanted to be when I was a child)

. Moest jij vorig weekend eten koken? +
  Nee, we hebben eten bezorgen gekocht. +
  Nee, we konden eten bezorgen kopen.

. Op welke leeftijd kon jij lezen? +
  Ik kon misschien op 5 jaar oud lezen. (need oud?)

. Moest jij vroeger op zaterdag naar school? +
  Ja, ik moest vroeger op zaterdag en soms zondag naar school.

==== Dialoog hoodstuk 11 (Opdracht 1 p. 159)

[cols=2]
|===
| Peter
| Hij is de vriend van Marit. Hij is accountant. Hij werkt niet meer op kantoor. Hij is eigen baas gewoorden. Hij heeft een eigen bedrijf. Hij heeft het druk. Hij verveelt zich nooit.

| Marit
| Zij is vandaag jarig. Zij is de buurvrouw van Tom. Zij is gek op Cubaanse muziek.

| Tom
| Hij is fietsenmaker. Hij is de buurman van Marit. Hij heeft Marit een kaartje voor Festival Cubana gegeven. (How to say he introduced himself to Kirsten / he knew Kirsten from the party?) Film en wandelen zijn zijn hobby's. Hij is gisteren naar de Wandelbeurs in Amsterdam geweest.

| Kirsten
| Zij is een vriendin van Marit. Zij komt uit Duitsland en woont sinds kort in Nederland. Zij studeert logopedie. Zij heeft een bijbaantje. Zij werkt iedere donderdag in de bioscoop. Film is niet haar hobby. Zij houdt van sport, van zwemmen en wandelen.

|===

=== Les 8 （13/12/2021）
==== p.164 oef 6
. Wat is er gebeurd? +
  Ik kan het *me* niet meer herinneren.
. Een wandelreis in Chili! Is wandelen daar geen probleem? +
  We gaan *ons* goed voorbereiden.
. Ze woont toch in Delft? +
  Nee echt niet, je vergist *je*.
. Hebben jullie *je* al voorgesteld? +
  Ja, dat hebben we al gedaan.
. Zijn ze weggegaan? +
  Ja, ze verveelden *zich*.
. Hebt u uw fiets bij *u*? +
  Nee, die heb ik naar de fietsenmaker gebracht.
. Hoe bevalt het Kirsten in Nederland? +
  Ze voelt *zich* hier al een beetje thuis. (wat betekent die?)
. Hoe kennen jullie *elkaar*? +
  Van de studie.
. Gaat hij niet mee naar de film? Of heeft hij de film al gezien? +
  Nee, hij interesseert *zich* niet voor dit soort films.

==== p.164 oef 7
Hij herinnert zich ook niets.
Hij herinnert zich het wachtwoord ook niet.

==== p.166 oef 8
. Wat voor muziek vind je leuk? +
  Ik interesseer me voor 80s en 90s pop muziek.
. Heb je altijd iets te doen? +
  Nee, soms verveel ik me een beetje.
. Het is vandaag toch zaterdag? +
  Nee, je vergist je. Het is zondag.
. Sorry, ik ken u niet, denk ik. Klopt dat? +
  Ja, laat me mezelf voorstellen. (klopt?)
. Weet je de naam van je eerste docent nog? +
  Nee, ik herinneer me dat niet.
. Waarom is Tanja vandaag niet in de les? +
  Zij voelt zich niet lekker.

==== p.173 hoofdstuk 12 Dialoog
de Evenementenhal
buschauffeur
instappen
tegenover
oversteken
plattegrond
beneden
rechtdoor

==== p.174 oef 1
. Waar heeft Kirsten gegaan?
. Wat heeft Kirsten je gevraagd? (aan je?)
. Kan je beter naar de evenementenhal lopen of met tram gaan?
. Met welke lijn mag Kirsten naar de evenementenhal gaan?
. Waar is de Wandelbeurs?
. Wat heeft de portier aan Kirsten gegeven?
. Waar zijn de toiletten?

Je mag niet de auto hier parkeren.
Dat mag. Dat mag niet.

=== Les 9 (17/01/2022)
==== p.177 Oef 4
7. We gingen met opdracht 14 verder. (gingen ver met ...)
8. Wie heeft een cadeau voor Marit meegenomen?
9. Kirsten is om 11.00 uur in Amsterdam aangekomen.
10. Waar ben je in gestapt.
11. Ik heb de koffie al afgerekend. betalen
12. We hebben in de Verenigde Staten ook samengewoond. (samengewoond ook?) not good

==== p.178 Oef 5
. Welke drie dingen heb je vandaag meegenomen in je tas? +
  Ik heb een telefoon, een laptop en een notitieboekje vandaag meegenomen in mijn tas. (een one time)
. Wat kun je opendoen? Noem drie dingen in je huis? +
  Ik kan het raam, de deur en de trekking opendoen in mijn huis.  (de la)
. Met welke dingen kun je verdergaan? Noem drie dingen. +
  Ik kan met de Nederlands les, de fotografie en de vergadering verdergaan.
. Wie kwam je gisteren tegen? Noem drie personen. +
  Ik kwam gisteren drie collega's tegen.
. Welke drie dingen kun je oversteken? +
  de straat, de grens en de rivier.
. Welke drie dingen heb je gisteren afgerekend? +
   het eten, de koffie en luiers voor Emmie.
. Met welke drie mensen wil je graag iets afspreken? (iets?) +
  Drie collega's van mijn team.

==== Oef 6
. Waarom heb je je telefoon uitgezet?
. Wanneer komen je ouders aan?
. Wanneer zullen we met de les verdergaan? (of verder gaan?)

==== p. 178 Oef 8
Beste Irina,

U moet bij Amsterdam Centraal Station uitstappen. Dan kunt u de tram 26 nemen. U moet bij Ijburg uitstappen. Die is de laatste halte van de lijn. De tram stopt naast een park, Theo van Goghpark. Mijn huis is aan de andere van het park.

Groeten,
Peter

==== p.179 Oef 9
. Vanaf welke leeftijd moet je een kaartje kopen? +
  13 jaar
. Kun je bij de Fiets en Wandelbeurs parkeren? +
  Ja
. Hoelang duurt de Fiets en Wandelbeurs? +
  De Fiets en Wandelbeurs duurt 7 uren.
. Je wil graag gaan fietsen in Nieuw-Zeeland. Is de Fiets en Wandelbeurs dan interessant voor jou? +



<<<

== Bijlage
=== Gammatica
* "ook" moet na werkwoorden. Ik bekijk ook de code.

=== Uitspraak
==== ie

|===
| ie -> [i:]  | lied, dieren
| ië -> [i-e] | Australië, België, Italië, Indonesië
|===

=== In de klas

|===
| Wij gaan door!
| Ok, dan gaan we door!
| Kun je de dialoog voorlezen?
| Wat zijn de verschillen tussen A en B?
| Twee vliegen in een klap
| Ik snap het!
| Ik begrijp het!
| Duidelijk!
| Ik wil me niet ergeren aan al die spullen, maar ik die het wel.
| Ik wil geen gevaarlijk dier zijn.
|===

=== Verstaan / Begrijpen niet (Nederlands in gang p.145)
*zeggen dat je iemand niet verstaat*

- Sorry, ik versta u niet goed. Kunt u het nog een keer zeggen?
- Kunt u het even herhalen?
- Wat zegt u?

*zeggen dat je iets / iemand niet begrijpt*

- Sorry, ik begrijp het niet. Wat bedoelt u met tiptop?

*vragen hoe je iets zegt in het Nederlands*

- Dat ding __. Hoe zeg je dat in het Nederlands?
- De bagagedrager, zeg je dat zo in het Nederlands?
- Hoe het dat / zo'n ding?

=== Links

https://www.youtube.com/watch?v=ZCA2DyqYvF0&ab_channel=LearnDutchwithBartdePau[Learn Dutch Alphabet + Pronunciation]

https://www.taal-oefenen.nl/[taal-oefenen.nl]

https://www.rekenen.nl/klokkijken/analoge-klok/[Klokkijken]

https://zichtbaarnederlands.nl/[Zichtbaar Nederlands.nl]
